#Gateway Properties
spring:
  application:
    name: Api-Gateway
  cloud:
    gateway:
      routes:
      - id: Employee-Service
        uri: lb://Employee-Service
        predicates:
        - Path=/employee/**
      - id: Training-Service
        uri: lb://Training-Service
        predicates:
        - Path=/training/**
